#!/usr/bin/env python

import gevent.monkey
gevent.monkey.patch_all()

from gevent.server import DatagramServer
from functools import partial
from sleepproxy import dnsserve, mdns

mdns.register_service(
    {
        'name': 'Sleep Proxy Server',
        'stype': '_sleep-proxy._udp',
        'domain': '',
        'host': '',
        'protocol': mdns.PROTO_INET,  # TODO: Support IP6
        'port': 52956,
    }
)
server = DatagramServer(('0.0.0.0', 52956), handle=dnsserve.handle)
server.set_handle(partial(dnsserve.handle, server))
server.serve_forever()
